project:
  type: website
  output-dir: _build
  resources:
    - examples/single-page
    - examples/pkgdown
    - examples/auto-package

execute:
  freeze: auto  # re-render only when source changes

metadata-files:
  - reference/_sidebar.yml

website:
  title: "prosodic"
  page-navigation: true
  navbar:
    left:
      - text: "Install"
        file: install.qmd
      - text: "Web App"
        file: webapp.qmd
      - text: "Quickstart"
        file: quickstart.qmd
      - text: "Example"
        file: example.qmd
      - text: "Architecture"
        file: architecture.qmd
      - text: "Reference"
        href: reference/

    right:
      - icon: github
        href: https://github.com/machow/quartodoc/


format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true


quartodoc:
  dir: reference
  package: prosodic
  parser: google
  sidebar: "reference/_sidebar.yml"
  sections:
    - title: API Refernce
      options:
        dynamic: true
      contents:
        - name: texts.Text
        - name: texts.Text.__init__
        - name: lines.Line
