project:
  type: website
  output-dir: _build
  resources:
    - examples/single-page
    - examples/pkgdown
    - examples/auto-package

metadata-files:
  - reference/_sidebar.yml

website:
  title: "quartodoc"
  page-navigation: true
  navbar:
    left:
      - text: "Quickstart"
        file: quickstart.qmd
      - text: "Tutorial"
        file: tutorial.qmd
      - text: "Reference"
        href: reference/

    right:
      - icon: github
        href: https://github.com/machow/quartodoc/


format:
  html:
    theme: cosmo
    toc: true


quartodoc:
  dir: reference
  package: prosodic
  parser: google
  sidebar: "reference/_sidebar.yml"
  sections:
    - title: API Refernce
      options:
        dynamic: true
      contents:
        - name: texts.Text
        - name: texts.Text.__init__
        - name: lines.Line
