name: "latest-release"

on:
  push:
    branches:
        - "develop"


# you need these permissions to publish to GitHub pages
permissions: 
    contents: write
    pages: write



jobs:
  tests:
    uses: "./.github/workflows/unit-tests.yml"  # use the callable tests job to run tests

  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
      


#   pre-release:
#     name: "Pre Release"
#     needs: [tests]
#     runs-on: "ubuntu-latest"
#     steps:
#         - name: "Releasing"
#           uses: "marvinpinto/action-automatic-releases@latest"
#           with:
#             repo_token: "${{ secrets.GITHUB_TOKEN }}"
#             automatic_release_tag: "latest"
#             prerelease: true
#             title: "Development Build"
